apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: diegosantos144/php:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: diegosantos144/meubanco:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306

      volumeMounts:
      - name: local
        mountPath: /var/lib/mysql
     volumes:
     - name: local
       hostPath:
        path: /meubanco/